cache: pip
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
stage: Test
install: pip install tox-travis coveralls
script: tox
after_success: coveralls

jobs:
  include:
    - stage: Lint and Format
      name: Lint
      script: tox -e lint
    - stage: Lint and Format
      name: Format
      script: tox -e format

    - stage: Release
      if: tag IS present
      script: tox -e py36
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: L/6hZ9YoZErGNTF3BlrcLqt73xR3UhGa9I6U4jI+Ut+po4xizgn69CLApx14NaVF677kJQJublNVo4VSP9HQ5q+vWO7bowLG13h0FmyBIRNbeDU2vLlC/jNCME/WZBA31unViOHRvaXVc3tpoLZ1CHm2LldeGIROSHVrzPJ6UtNBXCqfg6H2bRyEg/2W01dTyIaKNOIut9EgzyMmcbTyRsm8AsDB8vsgw96naPPh7NI+rUBQcVR2GR/T4CmyIlF23oZY+BOtuwWooOQRj5pUq0XAHPjun5SuqhIdzBlqHX7A35VLGsBYA2n0Q4/YKUMD41Gf2YGy54bkqwxpr/ZDIMPaJUu0yf5hZUpzmx1oeLGHNeIRqx0Cn/PSWrJCfjpmNxKUou6sqMw/4VGV6PtdrJn51oOg5ymaueSyUglAXekIWGBOui/yeDqTSFIMKD2x2uKSKqHRe/qaBxBOeLeWYiavtJ+15T+kgs+u0xUGqIY9NKR0kLvngSkVvJCXYwNfOvHaekQvHRE1BzTzYapdIheEyTBlP/u28TPWzOWmgVcy4ooLxSfPbBpmDHbGEaCqaO6UrHunTiPOrkbOvf7OdmDxWwReJdYZMjsnrjwZ/xSiwSuOLFT811vgOv7Y2qPXPPmiXgMpmkvJmYDbRmKLJgsLt2cVYwKzDnPUlNPF81M=
        edge: true
        skip_existing: true
        distributions: sdist bdist_wheel
        on:
          tags: true
          branch: master
          python: 3.6
