sudo: false
cache: pip

language: python

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install . --dev

# command to run tests
script:
  - pytest tests/lnmc_tests.py -vvs
  - pylint lnmc.py
