# AppVeyor recipe

# Not a VS project
build: off

environment:
  matrix:
    # List: https://www.appveyor.com/docs/installed-software/#python
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37"
      PYTHON VERSION: "3.7"
      PYTHON ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=lnmc -vvs
