# AppVeyor recipe

# Not a VS project
build: off

environment:
  matrix:
    # List: https://www.appveyor.com/docs/installed-software/#python
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39

init: ECHO %PYTHON% %PYTHON_VERSION% %HOMEDRIVE%%HOMEPATH%
install:
  - ps: python -W ignore -m pip install --upgrade pip
  - ps: python -W ignore -m pip install tox
test_script: tox
