name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup_python
        with:
          python_packages: "build"
      - name: 🧪 Run tests
        run: pytest
      - name: 📦 Build package
        run: python -m build --sdist --wheel --outdir dist/
      - name: 🚀 Publish package on PyPi
        uses: pypa/gh-action-pypi-publish@v1.10.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: 📝 Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generateReleaseNotes: true
          artifacts: "dist/*.whl"
